### ISSUE TITLE
TypeError: prepare is not a function

### ISSUE THREAD

**Issue by xehpuk** [WhoopInc/node-pg-range#6]
Using `pg-promise@8.2.2`:

```
TypeError: prepare is not a function
    at formatBound (...\node_modules\pg-range\lib\range.js:9:11)
    at PGRange.toPostgres (...\node_modules\pg-range\lib\range.js:33:5)
    at resolveFunc (...\node_modules\pg-promise\lib\formatting.js:275:23)
    at formatValue (...\node_modules\pg-promise\lib\formatting.js:63:28)
    at query.replace.name (...\node_modules\pg-promise\lib\formatting.js:176:24)
    at String.replace (<anonymous>)
    at Object.array (...\node_modules\pg-promise\lib\formatting.js:169:22)
    at Object.$formatQuery [as formatQuery] (...\node_modules\pg-promise\lib\formatting.js:300:29)
    at Task.$query (...\node_modules\pg-promise\lib\query.js:133:40)
    at Task.<anonymous> (...\node_modules\pg-promise\lib\query.js:259:23)
```

From their docs:
> Any value/object that implements function `toPostgres` is treated as a custom-formatting type. The function is then called to get the actual value, passing it the object via `this` context, and plus as a single parameter (in case `toPostgres` is an ES6 arrow function):
```js
const obj = {
    toPostgres(self) {
        // self = this = obj
        
        // return a value that needs proper escaping
    }
}
```

… and now I've seen that this has already been discussed in #5. So basically, `ng-promise` is incompatible with this library (and `node-postgres` w.r.t. `toPostgres`)?

**Comment by benesch** [comment]
> So basically, ng-promise is incompatible with this library (and node-postgres w.r.t. toPostgres)?

Afraid so. `pg` and `pg-promise` disagree on what the signature of `toPostgres` should be, and it's impossible to support both. It should be possible to create a shim that makes node-pg-range compatible, though:

```js
class PromiseRange extends pgRange.Range {
  toPostgres() {
    super.toPostgres(require('pg-promise').as.value)
  }
}
```

**Comment by benesch** [comment]
Closing due to inactivity. Feel free to open if the workaround doesn't meet your needs.
